var searchData=
[
  ['data_5ftoo_5flong_0',['data_too_long',['../class_codigo_q_r_1_1data__too__long.html',1,'CodigoQR::data_too_long'],['../class_codigo_q_r_1_1data__too__long.html#a431804a4016f75f17a13a02644a8ed6f',1,'CodigoQR::data_too_long::data_too_long()']]],
  ['datos_1',['Datos',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md11',1,'Capacidad de Datos'],['../estructuras.html',1,'Estructuras de Datos'],['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md40',1,'Validación de Datos']]],
  ['datos_20del_20qr_2',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['de_20clientes_3',['Gestion de Clientes',['../index.html#cliente_mod',1,'']]],
  ['de_20compilación_4',['Comandos de Compilación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md60',1,'']]],
  ['de_20cuenta_5',['Número de Cuenta',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md46',1,'']]],
  ['de_20cuenta_20_5finfo_20txt_6',['Información de Cuenta (&lt;span class=&quot;tt&quot;&gt;*_info.txt&lt;/span&gt;)',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md21',1,'']]],
  ['de_20cuentas_7',['Gestion de Cuentas',['../index.html#cuentas_mod',1,'']]],
  ['de_20datos_8',['de Datos',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md11',1,'Capacidad de Datos'],['../estructuras.html',1,'Estructuras de Datos'],['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md40',1,'Validación de Datos']]],
  ['de_20datos_20del_20qr_9',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['de_20encabezado_10',['Archivos de Encabezado',['../group___archivos_encabezado.html',1,'']]],
  ['de_20errores_11',['Corrección de Errores',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md13',1,'']]],
  ['de_20exportación_12',['Métodos de Exportación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md37',1,'']]],
  ['de_20generación_13',['Métodos de Generación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md35',1,'']]],
  ['de_20gestion_20bancaria_14',['Sistema de Gestion Bancaria',['../index.html',1,'']]],
  ['de_20información_20txt_15',['Archivo de Información (*.txt)',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md48',1,'']]],
  ['de_20la_20clase_16',['Uso de la Clase',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md14',1,'']]],
  ['de_20origen_17',['Archivos de Origen',['../group___archivos_origen.html',1,'']]],
  ['de_20problemas_18',['Resolución de Problemas',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md63',1,'']]],
  ['de_20referencia_20rápida_19',['GeneradorQRBanco - Guía de Referencia Rápida',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html',1,'']]],
  ['de_20salida_20',['Ejemplo de Salida',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md43',1,'']]],
  ['de_20uso_21',['Recomendaciones de Uso',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md26',1,'']]],
  ['de_20usuario_22',['Interfaz de Usuario',['../index.html#ui_mod',1,'']]],
  ['de_20validación_23',['Métodos de Validación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md36',1,'']]],
  ['de_20visualización_24',['Ejemplo de Visualización',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md51',1,'']]],
  ['del_20contenido_25',['Estructura del Contenido',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md42',1,'']]],
  ['del_20estándar_20iso_20iec_2018004_26',['1. Cumplimiento del Estándar ISO/IEC 18004',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md3',1,'']]],
  ['del_20qr_27',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['dependencias_28',['Dependencias',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md61',1,'']]],
  ['depositar_29',['depositar',['../class_cuenta.html#a1fdd97d3ef39c81820601098f4330c30',1,'Cuenta::depositar()'],['../class_cuenta_ahorros.html#a0d02e9c15deb0357dad0d7a2ba2abcf2',1,'CuentaAhorros::depositar()'],['../class_cuenta_corriente.html#a1b10f73a8f42786f7d5169c054cc952c',1,'CuentaCorriente::depositar()']]],
  ['desarrollo_30',['Para Desarrollo',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md28',1,'']]],
  ['desbloquear_31',['desbloquear',['../class_marquesina.html#a1e8de27731a32d4dc7a31c10625466c0',1,'Marquesina']]],
  ['descifrarsincargardatos_32',['descifrarSinCargarDatos',['../class_cifrado.html#a96f623add554f4e4653896f59a1f2e3b',1,'Cifrado']]],
  ['descifrarycargardatos_33',['descifrarYCargarDatos',['../class_cifrado.html#ae3a262fd643b343e371ba1256fe19a4a',1,'Cifrado']]],
  ['descripción_34',['Descripción',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md31',1,'']]],
  ['desifrararchivo_35',['desifrarArchivo',['../class_cifrado.html#a273e0d4695ff86f9f239821c298a8130',1,'Cifrado']]],
  ['detener_36',['detener',['../class_marquesina.html#a9fed251582657d7454cb3a06fbb1ee16',1,'Marquesina']]],
  ['diferencias_20con_20la_20versión_20anterior_37',['Diferencias con la Versión Anterior',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md23',1,'']]],
  ['documentación_3a_20generadorqrbanco_20optimizado_38',['Documentación: GeneradorQRBanco Optimizado',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html',1,'']]]
];
