var searchData=
[
  ['datos_0',['Datos',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md11',1,'Capacidad de Datos'],['../estructuras.html',1,'Estructuras de Datos'],['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md40',1,'Validación de Datos']]],
  ['datos_20del_20qr_1',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['de_20clientes_2',['Gestion de Clientes',['../index.html#cliente_mod',1,'']]],
  ['de_20compilación_3',['Comandos de Compilación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md60',1,'']]],
  ['de_20cuenta_4',['Número de Cuenta',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md46',1,'']]],
  ['de_20cuenta_20_5finfo_20txt_5',['Información de Cuenta (&lt;span class=&quot;tt&quot;&gt;*_info.txt&lt;/span&gt;)',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md21',1,'']]],
  ['de_20cuentas_6',['Gestion de Cuentas',['../index.html#cuentas_mod',1,'']]],
  ['de_20datos_7',['de Datos',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md11',1,'Capacidad de Datos'],['../estructuras.html',1,'Estructuras de Datos'],['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md40',1,'Validación de Datos']]],
  ['de_20datos_20del_20qr_8',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['de_20errores_9',['Corrección de Errores',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md13',1,'']]],
  ['de_20exportación_10',['Métodos de Exportación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md37',1,'']]],
  ['de_20generación_11',['Métodos de Generación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md35',1,'']]],
  ['de_20gestion_20bancaria_12',['Sistema de Gestion Bancaria',['../index.html',1,'']]],
  ['de_20información_20txt_13',['Archivo de Información (*.txt)',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md48',1,'']]],
  ['de_20la_20clase_14',['Uso de la Clase',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md14',1,'']]],
  ['de_20problemas_15',['Resolución de Problemas',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md63',1,'']]],
  ['de_20referencia_20rápida_16',['GeneradorQRBanco - Guía de Referencia Rápida',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html',1,'']]],
  ['de_20salida_17',['Ejemplo de Salida',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md43',1,'']]],
  ['de_20uso_18',['Recomendaciones de Uso',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md26',1,'']]],
  ['de_20usuario_19',['Interfaz de Usuario',['../index.html#ui_mod',1,'']]],
  ['de_20validación_20',['Métodos de Validación',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md36',1,'']]],
  ['de_20visualización_21',['Ejemplo de Visualización',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md51',1,'']]],
  ['del_20contenido_22',['Estructura del Contenido',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md42',1,'']]],
  ['del_20estándar_20iso_20iec_2018004_23',['1. Cumplimiento del Estándar ISO/IEC 18004',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md3',1,'']]],
  ['del_20qr_24',['Formato de Datos del QR',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md41',1,'']]],
  ['dependencias_25',['Dependencias',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md61',1,'']]],
  ['desarrollo_26',['Para Desarrollo',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md28',1,'']]],
  ['descripción_27',['Descripción',['../md__r_e_f_e_r_e_n_c_i_a___r_a_p_i_d_a.html#autotoc_md31',1,'']]],
  ['diferencias_20con_20la_20versión_20anterior_28',['Diferencias con la Versión Anterior',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html#autotoc_md23',1,'']]],
  ['documentación_3a_20generadorqrbanco_20optimizado_29',['Documentación: GeneradorQRBanco Optimizado',['../md__d_o_c_u_m_e_n_t_a_c_i_o_n___q_r___o_p_t_i_m_i_z_a_d_o.html',1,'']]]
];
